<?php
function thb_get_cta_templates($template_list) {
	$template_list['cta_01'] = array(
		'name' => esc_html__( 'Call To Action - 01', 'theissue' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demo_images/cta/01.jpg",
		'cat' => array( 'CTA' ),
		'sc' => '[vc_row content_placement="middle"][vc_column width="1/2" css=".vc_custom_1548507701198{padding-top: 5% !important;padding-bottom: 5% !important;}"][thb_slidetype slide_text="<h2>*Become a Member*</h2>"][vc_empty_space height="5px"][vc_column_text animation="animation fade-in"]Choose from our 6 and 12 month options and treat yourself or someone special. Subscribers enjoy free delivery.[/vc_column_text][thb_button style="style2" animation="animation fade-in" size="large" color="black" border_radius="no-radius" link="url:%23|title:Subscribe%20Now||"][/vc_column][vc_column width="1/2"][thb_image retina="retina_size" animation="animation fade-in" image="505"][/thb_image][/vc_column][/vc_row][vc_row css=".vc_custom_1548504948872{padding-bottom: 50px !important;}"][vc_column][vc_separator][/vc_column][/vc_row]',
	);
	$template_list['cta_02'] = array(
		'name' => esc_html__( 'Call To Action - 02', 'theissue' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demo_images/cta/02.jpg",
		'cat' => array( 'CTA' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1550142072863{padding-top: 60px !important;padding-bottom: 60px !important;background-color: #fbf0eb !important;}"][vc_column][vc_row_inner el_class="text-center"][vc_column_inner width="1/3" css=".vc_custom_1550134584217{padding-top: 250px !important;padding-bottom: 40px !important;background-image: url(https://theissue.fuelthemes.net/issue-03/wp-content/uploads/sites/3/2019/02/vt4.jpg?id=510) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][thb_button color="white" border_radius="pill-radius" link="url:%23|title:Shop%20Instagram||"][/vc_column_inner][vc_column_inner width="1/3" css=".vc_custom_1550139506215{padding-top: 250px !important;padding-bottom: 40px !important;background-image: url(https://theissue.fuelthemes.net/issue-03/wp-content/uploads/sites/3/2019/02/vt5.jpg?id=511) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][thb_button color="white" border_radius="pill-radius" link="url:%23|title:SEE%20ALL%20IDEAS||"][/vc_column_inner][vc_column_inner width="1/3" css=".vc_custom_1550139533146{padding-top: 250px !important;padding-bottom: 40px !important;background-image: url(https://theissue.fuelthemes.net/issue-03/wp-content/uploads/sites/3/2019/02/vt6.jpg?id=512) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][thb_button color="white" border_radius="pill-radius" link="url:%23|title:ABOUT%20ME||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['cta_03'] = array(
		'name' => esc_html__( 'Call To Action - 03', 'theissue' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demo_images/cta/03.jpg",
		'cat' => array( 'CTA' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1550746708192{background: #fdd73e url(https://theissue.fuelthemes.net/issue-09/wp-content/uploads/sites/9/2019/02/white_bar.png?id=555) !important;}" el_class="subscription-row"][vc_column][vc_row_inner content_placement="bottom"][vc_column_inner width="7/12"][thb_image image="540"][/thb_image][/vc_column_inner][vc_column_inner width="5/12" css=".vc_custom_1550747002737{padding-bottom: 50px !important;}"][vc_empty_space height="40px"][thb_slidetype slide_text="<h3>*Plus Membership*</h3>" style="style2"][vc_column_text animation="animation fade-in" css=".vc_custom_1550077065626{margin-bottom: 22px !important;}"]Subscribe to Issue and enjoy the following benefits:[/vc_column_text][vc_column_text animation="animation fade-in" css=".vc_custom_1550746677034{margin-bottom: 40px !important;}"]<ul><li>Get the first look at new issues, with all content available online before the print magazine arrives in stores.</li><li>Automatic renewals: never miss a story.</li></ul>[/vc_column_text][thb_button animation="animation fade-in" color="black" border_radius="no-radius" link="url:%23|title:UPGRADE%20NOW||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['cta_04'] = array(
		'name' => esc_html__( 'Call To Action - 04', 'theissue' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demo_images/cta/04.jpg",
		'cat' => array( 'CTA' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1551694296220{padding-top: 20vh !important;padding-bottom: 20vh !important;background: #040404 url(https://theissue.fuelthemes.net/issue-10/wp-content/uploads/sites/10/2019/02/cg5.jpg?id=535) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column thb_color="thb-light-column" el_class="text-center"][vc_row_inner el_class="align-center"][vc_column_inner offset="vc_col-lg-8 vc_col-md-10"][thb_fadetype fade_text="<h1>*Best Free Tools for Adding Dynamic Animations to UI*</h1>" style="style2"][vc_empty_space][thb_button style="style2" animation="animation fade-in" color="white" link="url:%23|title:Learn%20More||"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
	$template_list['cta_05'] = array(
		'name' => esc_html__( 'Call To Action - 05', 'theissue' ),
		'thumbnail' => Thb_Theme_Admin::$thb_theme_directory_uri."assets/img/admin/demo_images/cta/05.jpg",
		'cat' => array( 'CTA' ),
		'sc' => '[vc_row thb_full_width="true" thb_row_padding="true" thb_column_padding="true" css=".vc_custom_1551169299525{margin-top: 20px !important;margin-bottom: 60px !important;background: #f7f7f7 url(https://theissue.fuelthemes.net/issue-13/wp-content/uploads/sites/13/2019/02/issue_13_middle_bg.jpg?id=531) !important;background-position: center !important;background-repeat: no-repeat !important;background-size: cover !important;}"][vc_column][vc_row_inner content_placement="middle"][vc_column_inner el_class="text-center" width="1/2" css=".vc_custom_1551116302889{padding-top: 30px !important;padding-bottom: 30px !important;}"][thb_image retina="retina_size" animation="animation fade-in" alignment="aligncenter" image="533"][/thb_image][vc_empty_space height="15px"][thb_slidetype slide_text="<h1>*All IN ONE*</h1>"][vc_column_text animation="animation fade-in" css=".vc_custom_1551169118445{padding-right: 20% !important;padding-left: 20% !important;}"]<span style="font-size: 16px;">Wherein moved first gathered second cant first their thing, set was itself</span>[/vc_column_text][thb_button animation="animation fade-in" size="small" color="black" border_radius="no-radius" link="url:https%3A%2F%2Ftheissue.fuelthemes.net%2Fissue-13%2Fshop|title:SHOP%20NOW||"][/vc_column_inner][vc_column_inner width="1/2"][thb_hotspots thb_pin_color="pin-accent" animation="animation top-to-bottom" image="532" thb_hotspot_data="%5B%7B%22index%22%3A2%2C%22x%22%3A24.564873417721518%2C%22y%22%3A64.96155753968253%2C%22Product%22%3A%22286%22%2C%22Title%22%3A%22Tooltip%20title%22%2C%22Message%22%3A%22Tooltip%20content%20goes%20here%22%2C%22Position%22%3A%22top%22%7D%2C%7B%22index%22%3A3%2C%22x%22%3A83.90596745027125%2C%22y%22%3A75%2C%22Product%22%3A%22120%22%2C%22Title%22%3A%22Tooltip%20title%22%2C%22Message%22%3A%22Tooltip%20content%20goes%20here%22%2C%22Position%22%3A%22top%22%7D%5D"][/vc_column_inner][/vc_row_inner][/vc_column][/vc_row]',
	);
  return $template_list;
}